bodies: []
ghost objects:
- BODY ghost
soft bodies: []
joints: []
camera: []
lights: []
sensor: []
actuators: []
high resolution path: ./high_res/
low resolution path: ./low_res/
ignore inter-collision: true
namespace: /ambf/env/
gravity:
  x: 0.0
  y: 0.0
  z: 0.0
BODY ghost:
  name: ghost
  shape: BOX
  geometry: 
    x: 0.05
    y: 0.05
    z: 0.0045
  collision mesh type: CONVEX_HULL
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  passive: false
  collision shape: BOX
  collision geometry:
    x: 0.05
    y: 0.05
    z: 0.0045
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.0175
      g: 0.0401
      r: 0.8
    specular:
      b: 0.0201
      g: 0.0201
      r: 0.4
    transparency: 0.4357
